version: '3.8'
networks:
  shared:
    driver: bridge
services:
  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - distances_service
      - locations_service
    networks:
      - shared
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - shared
  distances_service:
    build:
      context: ./distances-service/
    command: poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8080
    volumes:
      - ./distances-service:/app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - shared
  locations_service:
    build:
      context: ./locations-service
    command: poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8081
    volumes:
      - ./locations-service:/app
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - shared
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - shared
  celery_worker:
    container_name: celery_worker
    build:
      context: ./distances-service/
    command: poetry run celery -A app.external_services.celery worker --pool=solo --loglevel=info
    volumes:
      - ./distances-service:/app
    depends_on:
      - redis
      - distances_service
    networks:
      - shared
volumes:
  dbdata: