version: '3.8'
networks:
  shared:
    driver: bridge
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - shared
  distances_service:
    build:
      context: ./distances-service/
    command: poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8080
    volumes:
      - ./distances-service:/app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - shared
  locations_service:
    build:
      context: ./locations-service
    command: poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8081
    volumes:
      - ./locations-service:/app
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - shared
volumes:
  dbdata: